### ISSUE TITLE
Keyword case-sensitivity

### ISSUE THREAD

**Issue by shiggins8** [SaulFemm/PlexHolidays#1]
First off, amazing tool. I'm a big fan. Possible suggestion/improvement: when a user enters a keyword, the script should work whether or not the keyword is capitalized. For example, I used "Christmas" as a keyword and the script found no matches, but when I used "christmas" it worked great. It seems that all of IMDB keywords or lower case (I didn't know that at first), but certain keywords (e.g. Christmas, Valentine's Day, Mother's Day, etc.) are traditionally typed in a capitalized format and this may be confusing for users. 

On line 90 of the script, just add ".lower()" after the input 

keyword = input("...").lower()

**Comment by cscattaglia917** [comment]
Same issue.

**Comment by SaulFemm** [comment]
Sorry about that, it was an obvious mistake. I actually fixed this in a0667a4 before just seeing this issue now. Thanks for the input!
